# Generated by Django 6.0.3 on 2026-04-03 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_id', models.PositiveIntegerField(help_text='ID del evento en el sistema de la compañera')),
                ('tipo_evento', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20)),
                ('titulo_evento', models.CharField(blank=True, help_text='Copia del título para mostrar mientras no hay integración', max_length=200)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('imagen_evento', models.URLField(blank=True)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_suscripcion'],
                'unique_together': {('usuario', 'evento_id', 'tipo_evento')},
            },
        ),
    ]
