# Generated by Django 6.0.3 on 2026-04-24 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('in_person_events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoPresencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_presenciales', to='in_person_events.event')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_presenciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito (Evento Presencial)',
                'verbose_name_plural': 'Favoritos (Eventos Presenciales)',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
