# Generated by Django 6.0.3 on 2026-04-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_suscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='titulo_evento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
