# Generated by Django 6.0.3 on 2026-05-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_favoritopresencial'),
        ('in_person_events', '0002_initial'),
        ('virtualEvent', '0003_virtualevent_final_elapsed_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='evento',
        ),
        migrations.AddField(
            model_name='consulta',
            name='evento_presencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='in_person_events.event'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='evento_virtual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='virtualEvent.virtualevent'),
        ),
        migrations.AddField(
            model_name='resena',
            name='evento_presencial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='in_person_events.event'),
        ),
        migrations.AddField(
            model_name='resena',
            name='evento_virtual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='virtualEvent.virtualevent'),
        ),
    ]
