# Generated by Django 6.0.3 on 2026-04-05 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resena'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-fecha_suscripcion']},
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='aprobado',
            new_name='aprobada',
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='titulo_evento',
            new_name='evento_titulo',
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='consulta',
            name='evento_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del evento relacionado (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='evento_titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resena',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resena',
            name='nombre',
            field=models.CharField(default='sin email', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta general'), ('soporte', 'Soporte técnico'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], default='consulta', max_length=20),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='evento_id',
            field=models.PositiveIntegerField(help_text='ID del evento (del sistema de compañeras)'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='suscripcion',
            unique_together={('usuario', 'evento_id', 'tipo_evento')},
        ),
    ]
