# Generated by Django 6.0.3 on 2026-04-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_resena_options_alter_suscripcion_options_and_more'),
        ('virtualEvent', '0002_eventanalytics_onlineviewer_eventview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='evento_id',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='evento_titulo',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='evento_id',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='evento_titulo',
        ),
        migrations.AddField(
            model_name='consulta',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='virtualEvent.virtualevent'),
        ),
        migrations.AddField(
            model_name='resena',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='virtualEvent.virtualevent'),
        ),
    ]
