# Generated by Django 6.0.3 on 2026-04-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_consulta_evento_id_and_more'),
        ('virtualEvent', '0002_eventanalytics_onlineviewer_eventview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='virtualEvent.virtualevent'),
            preserve_default=False,
        ),
    ]
