# Generated by Django 6.0.3 on 2026-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Evento')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente Aprobación'), ('aprobado', 'Aprobado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('visibility', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación/Dirección')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad Máxima')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de Fin')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historiales de Estados',
            },
        ),
    ]
