# Generated by Django 6.0.3 on 2026-04-30 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título del Recurso')),
                ('file', models.FileField(upload_to='event_resources/', verbose_name='Archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='in_person_events.event')),
            ],
            options={
                'verbose_name': 'Recurso de Evento',
                'verbose_name_plural': 'Recursos de Evento',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
