# Generated by Django 6.0.3 on 2026-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0002_eventresource'),
        ('in_person_events', '0002_initial'),
    ]

    operations = [
    ]
