# Generated by Django 6.0.3 on 2026-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0003_merge_0002_eventresource_0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_attendee_count',
            field=models.BooleanField(default=False, verbose_name='Mostrar recuento de asistentes'),
        ),
    ]
