# Generated by Django 6.0.3 on 2026-04-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtualEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streaming_room', to='virtualEvent.virtualevent')),
            ],
        ),
    ]
