# Generated by Django 6.0.3 on 2026-05-05 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0003_merge_0002_eventresource_0002_initial'),
        ('pe_registration', '0002_tickettype_quantity_available_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inscripción'),
        ),
        migrations.CreateModel(
            name='EventWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrada')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='in_person_events.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de Espera',
                'verbose_name_plural': 'Lista de Espera',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='unique_waitlist_per_event')],
            },
        ),
    ]
