# Generated by Django 4.2 on 2026-04-03 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('custom_category', models.CharField(blank=True, max_length=100, verbose_name='Categoría personalizada')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Imagen')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('privacy', models.CharField(choices=[('public', 'Público'), ('private', 'Privado (por invitación)')], default='public', max_length=10, verbose_name='Privacidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
