# Generated by Django 6.0.3 on 2026-04-22 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('custom_category', models.CharField(blank=True, max_length=100, verbose_name='Categoría personalizada')),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Imagen')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración (minutos)')),
                ('privacy', models.CharField(choices=[('public', 'Público'), ('private', 'Privado (por invitación)')], default='public', max_length=10, verbose_name='Privacidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('materials', models.JSONField(blank=True, default=dict, verbose_name='Material post-evento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de aprobación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_hands', models.PositiveIntegerField(default=0)),
                ('total_poll_votes', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('average_watch_time', models.FloatField(default=0.0, help_text='Minutos promedio por espectador')),
                ('average_satisfaction', models.FloatField(default=0.0, help_text='Promedio de 1 a 5')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='virtualEvent.virtualevent')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_viewers', to='virtualEvent.virtualevent')),
            ],
            options={
                'unique_together': {('event', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='virtualEvent.virtualevent')),
            ],
            options={
                'unique_together': {('event', 'session_key')},
            },
        ),
    ]
