# Generated by Django 4.2 on 2026-04-08 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('total_hands', models.PositiveIntegerField(default=0)),
                ('total_poll_votes', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('average_watch_time', models.FloatField(default=0.0, help_text='Minutos promedio por espectador')),
                ('average_satisfaction', models.FloatField(default=0.0, help_text='Promedio de 1 a 5')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='virtualEvent.virtualevent')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_viewers', to='virtualEvent.virtualevent')),
            ],
            options={
                'unique_together': {('event', 'session_key')},
            },
        ),
        migrations.CreateModel(
            name='EventView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='virtualEvent.virtualevent')),
            ],
            options={
                'unique_together': {('event', 'session_key')},
            },
        ),
    ]
