# Generated by Django 6.0.3 on 2026-04-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualEvent', '0002_eventanalytics_onlineviewer_eventview'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualevent',
            name='materials',
            field=models.JSONField(blank=True, default=dict, verbose_name='Material post-evento'),
        ),
    ]
