# Generated by Django 6.0.3 on 2026-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualEvent', '0002_virtualevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualevent',
            name='final_elapsed_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo total en segundos al finalizar el evento'),
        ),
    ]
