# Generated by Django 6.0.3 on 2026-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualEvent', '0003_virtualevent_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualevent',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de aprobación'),
        ),
        migrations.AddField(
            model_name='virtualevent',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
    ]
