# Generated by Django 6.0.3 on 2026-05-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='leido_por_admin',
            field=models.BooleanField(default=False),
        ),
    ]
