# Generated by Django 6.0.3 on 2026-04-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(db_index=True)),
                ('total_attendance', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('age_distribution', models.JSONField(default=dict)),
                ('gender_distribution', models.JSONField(default=dict)),
                ('ticket_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'verbose_name': 'Reporte Analítico',
                'verbose_name_plural': 'Reportes Analíticos',
                'ordering': ['-created_at'],
            },
        ),
    ]
