# Generated by Django 6.0.3 on 2026-04-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('in_person_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Actividad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('start_time', models.DateTimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Hora de Finalización')),
                ('location', models.CharField(max_length=255, verbose_name='Zona/Ubicación')),
                ('speaker_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Ponente')),
                ('speaker_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Ponente')),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='in_person_events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['event', 'start_time'], name='pe_agenda_a_event_i_a3bf52_idx'), models.Index(fields=['status'], name='pe_agenda_a_status_3a388c_idx')],
            },
        ),
    ]
