# Generated by Django 6.0.3 on 2026-05-02 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.PositiveIntegerField(verbose_name='ID de Actividad')),
                ('activity_title', models.CharField(max_length=200, verbose_name='Título de Actividad')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Suscripción')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción a Actividad',
                'verbose_name_plural': 'Suscripciones a Actividades',
                'ordering': ['-subscribed_at'],
                'unique_together': {('user', 'activity_id')},
            },
        ),
    ]
