# Generated by Django 6.0.3 on 2026-05-01 15:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ve_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handraise',
            name='raised_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
