# Generated by Django 6.0.3 on 2026-05-01 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ve_chat', '0002_handraise_raised_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='handraise',
            unique_together=set(),
        ),
    ]
