# Generated by Django 4.2 on 2026-04-08 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ve_chat', '0002_poll_polloption_satisfactionrating_pollvote_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='satisfactionrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='satisfactionrating',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
