# Generated by Django 6.0.3 on 2026-04-22 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('organizador', 'Organizador'), ('expositor', 'Expositor'), ('espectador', 'Espectador')], default='espectador', max_length=20, verbose_name='Rol')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'Prefiero no decirlo')], max_length=1, null=True, verbose_name='Sexo')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('biografia', models.TextField(blank=True, max_length=500, verbose_name='Biografía')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('eventos_asistidos', models.PositiveIntegerField(default=0, verbose_name='Eventos Asistidos')),
                ('eventos_organizados', models.PositiveIntegerField(default=0, verbose_name='Eventos Organizados')),
                ('recibir_notificaciones', models.BooleanField(default=True, verbose_name='Recibir Notificaciones')),
                ('recibir_newsletter', models.BooleanField(default=True, verbose_name='Recibir Newsletter')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='Última Actividad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaevento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuarios',
                'unique_together': {('usuario', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='preferencias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_prefieren', through='usuarios.PreferenciaUsuario', to='core.categoriaevento'),
        ),
    ]
