# Generated by Django 6.0.3 on 2026-04-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('organizador', 'Organizador'), ('expositor', 'Expositor'), ('espectador', 'Espectador')], default='espectador', max_length=20, verbose_name='Rol'),
        ),
    ]
