# Generated by Django 6.0.3 on 2026-04-29 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('in_person_events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('role', models.CharField(choices=[('LIDER_ZONA', 'Líder de Zona'), ('SOPORTE', 'Soporte Técnico'), ('RECEPCION', 'Recepción'), ('SEGURIDAD', 'Seguridad'), ('MONTAJE', 'Montaje'), ('CATERING', 'Catering'), ('ATENCION', 'Atención al Público')], max_length=50, verbose_name='Rol')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Token de Invitación')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aceptación')),
                ('expires_at', models.DateTimeField(verbose_name='Fecha de Expiración')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='in_person_events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Invitación de Staff',
                'verbose_name_plural': 'Invitaciones de Staff',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LIDER_ZONA', 'Líder de Zona'), ('SOPORTE', 'Soporte Técnico'), ('RECEPCION', 'Recepción'), ('SEGURIDAD', 'Seguridad'), ('MONTAJE', 'Montaje'), ('CATERING', 'Catering'), ('ATENCION', 'Atención al Público')], max_length=50, verbose_name='Rol')),
                ('zone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zona Asignada')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='in_person_events.event', verbose_name='Evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Miembro del Staff',
                'verbose_name_plural': 'Miembros del Staff',
                'ordering': ['role', 'zone'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
