# Generated by Django 6.0.3 on 2026-04-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinvitation',
            name='user_type',
            field=models.CharField(choices=[('ponente', 'Ponente'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='staffinvitation',
            name='role',
            field=models.CharField(blank=True, choices=[('LIDER_ZONA', 'Líder de Zona'), ('SOPORTE', 'Soporte Técnico'), ('RECEPCION', 'Recepción'), ('SEGURIDAD', 'Seguridad'), ('MONTAJE', 'Montaje'), ('CATERING', 'Catering'), ('ATENCION', 'Atención al Público')], max_length=50, null=True, verbose_name='Rol (solo para Staff)'),
        ),
    ]
