# Generated by Django 6.0.3 on 2026-05-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_staff', '0002_staffinvitation_user_type_alter_staffinvitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='user_type',
            field=models.CharField(choices=[('ponente', 'Ponente'), ('staff', 'Staff')], default='staff', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
