# Generated by Django 6.0.3 on 2026-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_staff', '0003_staffmember_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(blank=True, choices=[('LIDER_ZONA', 'Líder de Zona'), ('SOPORTE', 'Soporte Técnico'), ('RECEPCION', 'Recepción'), ('SEGURIDAD', 'Seguridad'), ('MONTAJE', 'Montaje'), ('CATERING', 'Catering'), ('ATENCION', 'Atención al Público')], max_length=50, null=True, verbose_name='Rol'),
        ),
    ]
