# Generated by Django 6.0.3 on 2026-05-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_agenda', '0002_activitysubscription'),
        ('pe_staff', '0004_update_role_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments', to='pe_agenda.activity', verbose_name='Actividad Asignada (Ponente)'),
        ),
    ]
