# Generated by Django 6.0.3 on 2026-04-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Stand')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Stands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.PositiveIntegerField(verbose_name='ID de Actividad')),
                ('scheduled_time', models.DateTimeField(verbose_name='Hora Programada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='pe_stand.stand', verbose_name='Stand')),
            ],
            options={
                'verbose_name': 'Actividad de Stand',
                'verbose_name_plural': 'Actividades de Stands',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='StandStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID de Usuario')),
                ('role', models.CharField(choices=[('Líder de Stand', 'Líder de Stand'), ('Especialista IT', 'Especialista IT'), ('Soporte Técnico', 'Soporte Técnico'), ('Recepción', 'Recepción'), ('Otro', 'Otro')], max_length=50, verbose_name='Rol')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='pe_stand.stand', verbose_name='Stand')),
            ],
            options={
                'verbose_name': 'Personal de Stand',
                'verbose_name_plural': 'Personal de Stands',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
