# Generated by Django 6.0.3 on 2026-04-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0001_initial'),
        ('pe_stand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='in_person_events.event', verbose_name='Evento'),
        ),
    ]
