# Generated by Django 6.0.3 on 2026-05-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_stand', '0002_stand_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standstaff',
            name='user_id',
        ),
        migrations.AddField(
            model_name='standstaff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stand_staff', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='standstaff',
            name='role',
            field=models.CharField(max_length=50, verbose_name='Rol'),
        ),
    ]
