# Generated by Django 6.0.3 on 2026-04-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pe_stand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Recurso')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='SKU')),
                ('category', models.CharField(choices=[('Mobiliario', 'Mobiliario'), ('Tech & AV', 'Tech & AV'), ('Catering', 'Catering'), ('Logística', 'Logística')], max_length=50, verbose_name='Categoría')),
                ('total_stock', models.PositiveIntegerField(verbose_name='Stock Total')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/items/', verbose_name='Imagen')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'name'], name='pe_inventor_categor_5eeffd_idx'), models.Index(fields=['sku'], name='pe_inventor_sku_64d63f_idx')],
            },
        ),
        migrations.CreateModel(
            name='StandAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Asignada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pe_inventory.item', verbose_name='Recurso')),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='pe_stand.stand', verbose_name='Stand')),
            ],
            options={
                'verbose_name': 'Asignación a Stand',
                'verbose_name_plural': 'Asignaciones a Stands',
                'ordering': ['-created_at'],
            },
        ),
    ]
