# Generated by Django 6.0.3 on 2026-05-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standassignment',
            name='details',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Detalles'),
        ),
    ]
