# Generated by Django 6.0.3 on 2026-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_inventory', '0002_standassignment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='standassignment',
            name='required_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Requerida'),
        ),
        migrations.AlterField(
            model_name='standassignment',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Asignada'),
        ),
    ]
