# Generated by Django 6.0.3 on 2026-05-07 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0004_event_show_attendee_count'),
        ('pe_inventory', '0003_standassignment_required_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='in_person_events.event', verbose_name='Evento'),
        ),
    ]
