# Generated by Django 6.0.3 on 2026-05-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_multiple_choice',
            field=models.BooleanField(default=False, verbose_name='Permitir Múltiples Opciones'),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('escala', 'Escala 1-5'), ('texto', 'Texto con Opciones')], default='escala', max_length=20, verbose_name='Tipo de Encuesta'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.JSONField(verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='delivery_type',
            field=models.CharField(choices=[('inmediato', 'Inmediato'), ('programado', 'Programado')], default='inmediato', max_length=20, verbose_name='Tipo de Entrega'),
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Opción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pe_surveys.survey', verbose_name='Encuesta')),
            ],
            options={
                'verbose_name': 'Opción de Encuesta',
                'verbose_name_plural': 'Opciones de Encuesta',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
