# Generated by Django 6.0.3 on 2026-05-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pe_surveys', '0002_remove_response_question_remove_survey_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyoption',
            options={'verbose_name': 'Opción de Encuesta', 'verbose_name_plural': 'Opciones de Encuesta'},
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='order',
        ),
    ]
