# Generated by Django 6.0.3 on 2026-05-06 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_person_events', '0004_event_show_attendee_count'),
        ('pe_surveys', '0004_survey_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='event',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='in_person_events.event', verbose_name='Evento'),
            preserve_default=False,
        ),
    ]
