# Generated by Django 6.0.3 on 2026-05-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pe_surveys', '0005_alter_survey_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío'),
        ),
    ]
