# Generated by Django 6.0.3 on 2026-04-29 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Plantilla')),
                ('template_type', models.CharField(choices=[('staff_invitation', 'Invitación de Staff'), ('staff_accepted', 'Confirmación de Aceptación'), ('staff_assigned', 'Asignación de Zona'), ('event_confirmation', 'Confirmación de Evento'), ('event_reminder', 'Recordatorio de Evento')], max_length=50, verbose_name='Tipo')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('body_html', models.TextField(verbose_name='Cuerpo HTML')),
                ('body_text', models.TextField(verbose_name='Cuerpo Texto Plano')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Plantilla de Email',
                'verbose_name_plural': 'Plantillas de Email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinatario')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='pe_communication.emailtemplate', verbose_name='Plantilla Usada')),
            ],
            options={
                'verbose_name': 'Registro de Email',
                'verbose_name_plural': 'Registros de Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
